version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: inventory-management
    container_name: inventory-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped